Fs librdkafka as submodule
swift-server/swift-kafka-gsoc pull request #50
Opened 2023-04-15 12:12 UTC by felixschlegel

### Motivation

Previously users of our Package had to install `librdkafka` through their package managers to be able to run this package, as we relied on linking `librdkafka` **dynamically**.

With this PR, we ship `librdkafka` as a **git submodule** that is then built with SPM. This overcomes the issues we previously had with dynamic linking (e.g. not finding header files etc.).

### Modifications:

* add `librdkafka` submodule to project
* create a hardcoded `config.h` file that contains information on how
  `librdkafka` should be compiled (normally this is done through a the
`librdkafka/configure.sh` script, though we cannot invoke this at
buildtime with SPM)
* add package dependencies to `zstd` and `swift-nio-ssl`
* build `librdkafka` package with SPM instead of relying on a
  `.systemLibary` target
* create bridge between `<openssl/*>` headers and `swift-nio-ssl` with
  `custom` include folder
* update Docker to install zlib
* remove librdkafka from Docker
* create hard-coded `config.h` file that is used to compile librdkafka
* automatically update submodule from Docker

### Known Issues

* our Package assumes that `zlib`, `curl` and `sasl` are already installed on the system we are building on
* the new build process has **not** been tested on **x86_64**
* to build `librdkafka`, a config script has to be run that creates a file called `config.h` that configures the `lirbdkafka` build according to the underlying system, as we cannot run a build-script with SPM (I think 😅) I hardcoded this `config.h` file to build `librdkafka` with a very generalised configuration (See: [Building librdkafka](https://github.com/confluentinc/librdkafka#building))
* at the moment, our [facebook/zstd](https://github.com/facebook/zstd) dependency throws out a lot of build warnings, however, this is a know issue: https://github.com/facebook/zstd/issues/3328

2023-04-27 08:31 UTC, FranzBusch requested changes
This is great! It will make working with this package a lot easier. I left some inline comments that we need to address. Furthermore, we need to add a notice file similar to [this](https://github.com/apple/swift-cassandra-client/blob/main/NOTICE.txt)

2023-05-04 09:19 UTC, felixschlegel commented on Sources/Crdkafka/librdkafka
Yes, now we are pointing at [librdkafka-v2.1.1](https://github.com/confluentinc/librdkafka/releases/tag/v2.1.1)

2023-05-04 09:21 UTC, felixschlegel commented on Package.swift
> +        .package(url: "https://github.com/apple/swift-nio-ssl.git", .upToNextMajor(from: "2.21.0")),
I talked to @lukasa, and our new approach is to have `openssl` as a `.systemLibrary` target.

2023-05-04 09:22 UTC, felixschlegel commented on Package.swift
> +        // The zstd Swift package produces warnings that we cannot resolve:
Just warnings ⚠️ :

```bash
/swift-kafka-gsoc/Sources/Crdkafka/librdkafka/src/rdkafka_zstd.c:38:2: warning: definition of configuration macro 'ZSTDLIB_VISIBLE' has no effect on the import of 'libzstd.errors'; pass '-DZSTDLIB_VISIBLE=...' on the command line to configure the module [-Wconfig-macros]
#include <zstd_errors.h>
 ^
/swift-kafka-gsoc/.build/checkouts/zstd/lib/zstd.h:28:13: note: macro was defined here
#    define ZSTDLIB_VISIBLE __attribute__ ((visibility ("default")))
            ^
/swift-kafka-gsoc/Sources/Crdkafka/librdkafka/src/rdkafka_zstd.c:38:2: warning: definition of configuration macro 'ZSTDLIB_HIDDEN' has no effect on the import of 'libzstd.errors'; pass '-DZSTDLIB_HIDDEN=...' on the command line to configure the module [-Wconfig-macros]
#include <zstd_errors.h>
 ^
/swift-kafka-gsoc/.build/checkouts/zstd/lib/zstd.h:36:13: note: macro was defined here
#    define ZSTDLIB_HIDDEN __attribute__ ((visibility ("hidden")))
            ^
/swift-kafka-gsoc/Sources/Crdkafka/librdkafka/src/rdkafka_zstd.c:38:2: warning: definition of configuration macro 'ZSTD_CLEVEL_DEFAULT' has no effect on the import of 'libzstd.errors'; pass '-DZSTD_CLEVEL_DEFAULT=...' on the command line to configure the module [-Wconfig-macros]
#include <zstd_errors.h>
 ^
/swift-kafka-gsoc/.build/checkouts/zstd/lib/zstd.h:129:11: note: macro was defined here
#  define ZSTD_CLEVEL_DEFAULT 3
          ^
/swift-kafka-gsoc/Sources/Crdkafka/librdkafka/src/rdkafka_zstd.c:38:2: warning: definition of configuration macro 'ZDICTLIB_VISIBLE' has no effect on the import of 'libzstd.errors'; pass '-DZDICTLIB_VISIBLE=...' on the command line to configure the module [-Wconfig-macros]
#include <zstd_errors.h>
 ^
/swift-kafka-gsoc/.build/checkouts/zstd/lib/zdict.h:28:13: note: macro was defined here
#    define ZDICTLIB_VISIBLE __attribute__ ((visibility ("default")))
            ^
/swift-kafka-gsoc/Sources/Crdkafka/librdkafka/src/rdkafka_zstd.c:38:2: warning: definition of configuration macro 'ZDICTLIB_HIDDEN' has no effect on the import of 'libzstd.errors'; pass '-DZDICTLIB_HIDDEN=...' on the command line to configure the module [-Wconfig-macros]
#include <zstd_errors.h>
 ^
/swift-kafka-gsoc/.build/checkouts/zstd/lib/zdict.h:36:13: note: macro was defined here
#    define ZDICTLIB_HIDDEN __attribute__ ((visibility ("hidden")))
            ^
/swift-kafka-gsoc/Sources/Crdkafka/librdkafka/src/rdkafka_zstd.c:38:2: warning: definition of configuration macro 'ZSTDERRORLIB_VISIBLE' has no effect on the import of 'libzstd.errors'; pass '-DZSTDERRORLIB_VISIBLE=...' on the command line to configure the module [-Wconfig-macros]
#include <zstd_errors.h>
 ^
/swift-kafka-gsoc/.build/checkouts/zstd/lib/zstd_errors.h:28:13: note: macro was defined here
#    define ZSTDERRORLIB_VISIBLE __attribute__ ((visibility ("default")))
            ^
/swift-kafka-gsoc/Sources/Crdkafka/librdkafka/src/rdkafka_zstd.c:38:2: warning: definition of configuration macro 'ZSTDERRORLIB_HIDDEN' has no effect on the import of 'libzstd.errors'; pass '-DZSTDERRORLIB_HIDDEN=...' on the command line to configure the module [-Wconfig-macros]
#include <zstd_errors.h>
 ^
/swift-kafka-gsoc/.build/checkouts/zstd/lib/zstd_errors.h:36:13: note: macro was defined here
#    define ZSTDERRORLIB_HIDDEN __attribute__ ((visibility ("hidden")))
```

2023-05-04 09:25 UTC, felixschlegel commented on Package.swift
> +
The `.when(...)` approach works for the target platform, though I have not yet found a better way to find out the target `arch` in SwiftPM 😅

2023-05-04 09:28 UTC, felixschlegel commented
cc: @lukasa @gjcairo

I have implemented the changes that @FranzBusch has requested. Regarding the [`NOTICE.txt`](NOTICE.txt) file, I don't know if that is legally correct so I would be happy if you could double-check that 😅 

Cheers,
Felix

2023-05-08 18:04 UTC, tomerd commented on Package.swift
> +                .linkedLibrary("z"), // zlib
where do these come from? system dependencies?

2023-05-08 18:06 UTC, tomerd commented on Sources/Crdkafka/custom/config/x86_64/macOS/config.h
> +#endif /* _CONFIG_H_ */
are these all generated by kayaks build process ie by running `./configure` for the platform in question?

2023-05-08 18:07 UTC, tomerd commented on Package.swift
> +        // The zstd Swift package produces warnings that we cannot resolve:
cc @yim-lee

2023-05-11 16:20 UTC, yim-lee commented
@swift-server-bot test this please

2023-05-12 09:14 UTC, FranzBusch approved these changes
LGTM!

2023-05-12 09:15 UTC, merged