`KafkaConsumerConfig` add `SwiftKafka` options
swift-server/swift-kafka-gsoc pull request #54
Opened 2023-06-02 17:31 UTC by felixschlegel

### Motivation

We want to use the `KafkaConsumerConfig` to determine if the `KafkaConsumer` is part of a consumer-group (subscription) or assigned to a single topic partition (assignment). This should also be implemented so that errors are caught at compile time. Furthermore, we want users to be able to determine a `BackPressureStrategy` for their respective `KafkaClient`.

### Modifications

* add two new configuration options to `KafkaConsumerConfig`: `ConsumptionStrategy` and `BackPressureStrategy`
* remove `KafkaConsumerConfig`'s `groupID` option. This is now taken care of by the `consumptionStrategy` option, which is better as this ensures at compile time that now groupID mismatch errors occur
* rename `KafkaProducerConfig` back to `ConfigEnums` as it is not really meant for shared configurations, but rather as a namespace for _all_ configuration options
* update README

2023-06-06 15:38 UTC, FranzBusch requested changes

2023-06-06 15:38 UTC, FranzBusch commented on Sources/SwiftKafka/Configuration/ConfigEnums.swift
>      /// Available debug contexts to enable.
This seems wrong

2023-06-06 15:38 UTC, FranzBusch commented on Sources/SwiftKafka/Configuration/KafkaConsumerConfig.swift
> +        public static func highLowWatermark(lowWatermark: Int, highWatermark: Int) -> BackPressureStrategy {
Let's rename this
```suggestion
        public static func watermark(low: Int, high: Int) -> BackPressureStrategy {
```

2023-06-08 13:23 UTC, FranzBusch commented on Sources/SwiftKafka/Configuration/KafkaConsumerConfig.swift
> +        /// - Parameter highWatermark: The upper threshold for the buffer size.
Can we update the parameter names

2023-06-09 13:56 UTC, felixschlegel commented
> Almost there just some doc comment nits

Arrgh! Fixed it ✅

2023-06-14 08:33 UTC, FranzBusch approved these changes

2023-06-14 08:35 UTC, merged