KafkaProducer: Expose `run()` method
swift-server/swift-kafka-gsoc pull request #63
Opened 2023-06-14 15:04 UTC by felixschlegel

### Modifications

* fix typo in `SwiftKafkaTests`
* upgrade minimum OS versions to support the `Duration` type
* move conversion of `rd_kafka_message_t` to `KafkaAcknowledgementResult` to `RDKafkaConfig` so that we can pass the `KafkaAcknowledgementResult` type as early as possible and don't have to bother with `UnsafePointer<rd_kafka_message_t>` in all our delivery callback logic
* expose KafkaProducer.run() method
* `README`: use `TaskGroup` in `KafkaProducer` example
* add comments to task groups in `README`
* refactor all tests into using task groups (structured concurrency)

## Have two factory methods creating KafkaProducer

### Motivation

We want to have a `KafkaProducer` that is not consuming any acknowledgements. This means it is initialized without a `deliveryReportCallback` which in turn means that `librdkafka` will not queue any incoming acknowledgements which prevents us from running out of memory in that case.

### Modifications

* add two new factory methods for creating `KafkaProducer`: * `KafkaProducer.newProducer` * `KafkaProducer.newProducerWithAcknowledgements`
* update README

2023-06-15 10:16 UTC, FranzBusch commented on Sources/SwiftKafka/KafkaProducer.swift
> +    private var polling = true
We don't need this property. We can use the state for this `started` indicates that we are polling

2023-06-15 12:09 UTC, FranzBusch requested changes

2023-06-15 12:09 UTC, FranzBusch commented on Sources/SwiftKafka/KafkaProducer.swift
> +                _ = source.yield(messageResult) // Ignore YieldResult
Let's add why we ignore this result i.e. due to no back pressure support.

2023-06-15 16:39 UTC, felixschlegel commented on Sources/SwiftKafka/KafkaProducer.swift
> +    private let client: KafkaClient
https://github.com/swift-server/swift-kafka-gsoc/issues/64

2023-06-15 17:01 UTC, felixschlegel commented on Sources/SwiftKafka/KafkaProducer.swift
> +    /// - Throws: A ``KafkaError`` if initializing the producer failed.
https://github.com/swift-server/swift-kafka-gsoc/pull/65

2023-06-19 12:02 UTC, FranzBusch approved these changes

2023-06-19 12:02 UTC, merged